config/routes.rb
MyGists::Application.routes.draw do
  get "gists/search"
  resources :gists
  root 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
	validates :snippet, presence: true,
	                    length: { minimum: 3 }
	validates :description, presence: true,
	                    length: { minimum: 1 }

    def self.search(search)
      if search
        find(:all, :conditions => ['snippet LIKE ?', "%#{search}%"])
      else
        limit(0)
      end
    end
end

app/models/grant.rb
def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['snippet LIKE ?', search_condition])
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.paginate(page: params[:page], per_page: 10).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

   def search
    @gists = Gist.search(params[:search])
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
<%
  all_lexers = Pygments.lexers.flatten.select.with_index(offset = 0) { |x,i| i % 2 == 0 }.sort 
  all_lexers = all_lexers.delete_if { |x| x =~ /.\s./ }
  all_lexers = all_lexers.map { |x| x.downcase }
%>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet, :size => "45x20",placeholder: 'Enter your code here...'  %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.select :lang, all_lexers %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, size: 25, maxlength: 50 %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div> 

<% end %>

app/views/gists/_gist.html.erb
  <div id="gist">
     <div id="snippet">
       <div class="ih"><strong>Snippet</strong><hr/></div>
       <%= raw Pygments.highlight(gist.snippet.length > 25 ? gist.snippet[0,25] + "..." : gist.snippet, lexer: gist.lang) %>
     </div> 
    <strong>Lang:</strong> <%= gist.lang %><br><br>
  
    <%= link_to 'Show', gist,  :class => 'action2'  %>
    <%= link_to 'Edit', edit_gist_path(gist),  :class => 'action2'  %>
    <%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' },  :class => 'action2'  %>
  </div>         

app/views/gists/edit.html.erb
<div class="page_header">
  <h1>My gists</h1>
</div><br>

<div class="without_header">
  <%= link_to 'Home', gists_path ,  :class => 'action2'  %>
   <%= link_to 'New', new_gist_path,  :class => 'action2'  %>
   <%= link_to 'Search', gists_search_path,  :class => 'action2'  %>
   <br>

  <h1 id="title">Editing gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path,  :class => 'action2'  %><br>

</div>

app/views/gists/index.html.erb
<div class="page_header">
  <h1>My gists</h1>
</div><br>

<div class="without_header">
  <%= link_to 'Home', gists_path ,  :class => 'action2'  %>
   <%= link_to 'New', new_gist_path,  :class => 'action2'  %>
   <%= link_to 'Search', gists_search_path,  :class => 'action2'  %>
   <br><br>

<div id="infinite-scrolling">
   <%= will_paginate %>
</div>

<div id="my-gists"> 
    <%= render @gists %>
</div>

</div>

app/views/gists/index.js.erb
var delimiter =
$('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#my-gists').append(delimiter);
$('#my-gists').append('<%= j render @gists %>');
$('.pagination').replaceWith('<%= j will_paginate @gists %>');
preparePagination(delimiter);

<% unless @gists.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/gists/new.html.erb
<div class="page_header">
  <h1>My gists</h1>
</div><br>

<div class="without_header">
  <%= link_to 'Home', gists_path ,  :class => 'action2'  %>
   <%= link_to 'New', new_gist_path,  :class => 'action2'  %>
   <%= link_to 'Search', gists_search_path,  :class => 'action2'  %>
   <br>

<h1>New gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path,  :class => 'action2'  %><br>
</div>

app/views/gists/search.html.erb
<div class="page_header">
  <h1>My gists</h1>
</div><br>

<div class="without_header">
  <%= link_to 'Home', gists_path ,  :class => 'action2'  %>
   <%= link_to 'New', new_gist_path,  :class => 'action2'  %>
   <%= link_to 'Search', gists_search_path,  :class => 'action2'  %><br><br>
  <form role="search">
    <div id="search">
      <%= submit_tag "Search", :snippet => nil  %>
    </div>
    <div id="search">
      <%= text_field_tag :search, params[:search] %>
    </div>  
  </form><br><br> <br>

<div id="my-gists"> 
    <%= render @gists %>
</div>

</div>

app/views/gists/show.html.erb
<div class="page_header">
  <h1>My gists</h1>
</div><br>

<div class="without_header">
  <%= link_to 'Home', gists_path ,  :class => 'action2'  %>
   <%= link_to 'New', new_gist_path,  :class => 'action2'  %>
   <%= link_to 'Search', gists_search_path,  :class => 'action2'  %>
   <br><br>

<p id="notice"><%= notice %></p>
<strong>Snippet:</strong>
<%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
<strong>Lang:</strong>
<%= @gist.lang %>

<p>
  <strong>Description:</strong>
  <%= @gist.description %>
</p>

<%= link_to 'Edit', edit_gist_path(@gist),  :class => 'action2'  %>
<%= link_to 'Back', gists_path,  :class => 'action2'  %>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>My gists </title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>